security:

    providers:
        id:
            entity:
                class: App\Entity\User
                property: id
        username:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/auth
            stateless: true
            anonymous: true
            provider: username
            json_login:
                check_path: /auth
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/
            anonymous: true
            stateless: true
            provider: id
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true

    access_control:
        - { path: ^/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
